unique: something

appSet:
  name: app-set-int
  image: image-int
  imageTag: image-tag

helmRoot: |
  secondObj: 
    intprop: myprop1
    intprop1: myprop12
  firstObj: 
    intprop: myprop1
    intprop1: myprop12
